### ISSUE TITLE
[go] Create vanity for go.wrpc

### ISSUE THREAD

**Issue by ricochet** [bytecodealliance/wrpc#28]
Since we believe wRPC will be a foundational mutli-stakeholder project, there's a good chance it may be moved to another organization. We can keep from modifying our code if a transition occurs by providing a vanity url.

Create a vanity URL with github pages to `go.wrpc.io`. 

The go work is currently in a subdir at `github.com/wrpc/wrpc/go`. If we use github pages, we need to test if we can host an index.html using [modgen](https://github.com/essaim-dev/modgen) so that `go.wrpc.io -> wrpc.github.io/wrpc/go`

**Comment by rvolosatovs** [comment]
what we can do without running a custom go module proxy is `wrpc.io/go`, which I have set up using https://github.com/wrpc/wrpc.io in #269 

Perhaps in the future we can revisit this (e.g. for 1.0) and, if we have resources, run a `go.wrpc.io` proxy to improve this further
