### ISSUE TITLE
where to find quickstart guide about running the examples?

### ISSUE THREAD

**Issue by sammyne** [bytecodealliance/wrpc#286]
Really appreciate if there is a guide helping me to build examples and run them~

**Comment by rvolosatovs** [comment]
Thanks for filing an issue, indeed - documentation is currently lacking

Native wRPC applications in Rust are runnable using `cargo run` from the example directory or via `cargo run -p streams-nats-server`, for example

Rust component examples need to be built for `wasm32` and then can be run via e.g. `wrpc-wasmtime-nats` provided in this repository

Go examples should be runnable similarly via `go run`

Most examples will require a running `nats-server` currently

**Comment by sammyne** [comment]
A quickstart guide has been posted as this PR https://github.com/bytecodealliance/wrpc/pull/294

**Comment by rvolosatovs** [comment]
Done in #294, small update in #300
